### ISSUE TITLE
Task: Delete Sticky Note

### ISSUE THREAD

**Issue by sleepGuyWD** [raswonders/sticky-notes#13]
Allow user to delete a selected sticky note.

- (Idea) Maybe think of how a user could delete multiple at once. 
    * Delete All, Delete Selected features?

**Comment by raswonders** [comment]
renamed and added milestone v1

**Comment by raswonders** [comment]
I think selecting/deleting multiple is kind of advanced feature maybe next iteration?

**Comment by raswonders** [comment]
I'm gonna attempt to close it with basic UI Cross which appears on hover. I have no better idea at the moment and it doesn't seem as too difficult.
