### ISSUE TITLE
Task: Rearrange Sticky Notes

### ISSUE THREAD

**Issue by sleepGuyWD** [raswonders/sticky-notes#14]
Allow user to rearrange sticky notes.

Refer to Youtube Vid: https://www.youtube.com/watch?v=jfYWwQrtzzY

**Comment by raswonders** [comment]
renamed added milestone v1 and enhacement tag

**Comment by sleepGuyWD** [comment]
Started this feature.  Have to head to bed.  Ended around 6:02 time stamp of the video in main description ^^

**Comment by raswonders** [comment]
so I've thought about starting on it but realized layout was just making things really complicated. Hence I've changed it to absolute positioning. It should be easier to do drag & drop but I'm out of time now. I'll be able to continue in evening if noone picks this up.
