### ISSUE TITLE
Task: use localStorage to load/save notes

### ISSUE THREAD

**Issue by raswonders** [raswonders/sticky-notes#29]

**Comment by sleepGuyWD** [comment]
Local storage feature was implemented  onto localStorage branch. Pushed upstream.

I have an issue with loading saved date and all sticky notes move upwards a couple pixels.


See vid:
https://github.com/raswonders/sticky-notes/assets/107953410/2144dc55-30d3-4289-83c8-668965df861c

**Comment by raswonders** [comment]
I don't see it. I don't think the branch made it to upstream repo.

**Comment by raswonders** [comment]
I fixed the bug with note offset, and another bug when notes where decreasing in number every refresh. I've also moved session related code to its own module. Last thing I need to figure out is out to pull previous changes from main and apply them before we merge.
